### PR TITLE
Task 4: ScrollView Homepage

### LINKED ISSUE #4: on home screen implement a scroll view that we can populate with buttons
This one should allow for buttons or other elements to be added to it later so that if we decide on adding more than 6 buttons users can scroll down to see the rest.
image

### PR DESCRIPTION
**Pull request by Oxbower**
- Removed the 'Hello World' at the centre of home page
- Added a ScrollView container to the homepage
- Added an insertion point to the ScrollView in BaseActivity.java for dynamically created buttons
- Added placeholder buttons to show scrolling functionality (you need to drag up and down when trying it out since its a mobile app, Remove this when creating the actual buttons)

### CODE REVIEW

**Comment by Oxbower** [comment]
Hey, I just realized the BaseActivity.java was for reusing the top and bottom bar, just exclude my commits to that file, I did not change anything only added an entry point for the buttons

**Comment by nathanbowley98** [comment]
everything looks good I think from when i checked out the branch, but what do you mean exclude those commits?

**Comment by Oxbower** [comment]
delete the commit I made into BaseActivity.java in the 'Files Changed' tab up top so it reverts back to the original, its not really a big deal, it was just a function you can call to insert dynamically built buttons into the scrollview I only realized BaseActivity.java was for reusable header and footer after already making a pr, I should have moved the function to a class to handle button insertion.

**Comment by nathanbowley98** [comment]
Ohhh, I see, ill fix this tomorrow, thanks for letting me know,

Sincerely,
Nathanael
________________________________

**Pull request merged**
